# server setting
server:
  port: 18809

# spring-boot setting
spring:
  application:
    name: interview-online
  # mysql setting
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://107.172.180.188:3306/interview_system?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: normal
    password: AdTime06@17

  # redis setting
  redis:
    host: 107.172.180.188
    port: 6379
    password: redis@1012
    database: 1
    timeout: 5s
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 60000
        max-wait: -1ms

  # jackson setting
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    # multipart file setting
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

# mybatis setting
mybatis:
  # 配置别名
  type-aliases-package: org.interview.entity
  # 配置mapper映射文件路径
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    # 配置下划线转驼峰
    map-underscore-to-camel-case: true
    # 开启缓存
    cache-enabled: true

# mybatis-plus setting
mybatis-plus:
  type-aliases-package: org.interview.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      logic-delete-field: delFlag # 全局逻辑删除的实体字段名（since 3.3.0，配置后可以忽略不配置步骤2）
      logic-delete-value: 1 # 配置逻辑删除值
      logic-not-delete-value: 0 # 配置逻辑未删除值

resume-file:
  path: "D:\\项目code\\Java\\project\\File"

# jwt setting
jwt:
  tokenHeader: "Authenrization"
  tokenPrefix: "JwtAuth "
  # 签发者
  iss: "woo"
  # secret key
  secret: "woo_system@"
  # redis cache key prefix
  cacheKeyPrefix: "JwtAuth:"
  # 登录有效时间
  loginValidateTime: 2h
  # "记住我"有效时间
  rememberValidateTime: 3d
  # 登录刷新时间
  loginRefreshLimit: 45m
  # token有效时间
  tokenExpireTime: 1d
